Models/Livro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EsseJaLi.Models
{
    public class LivrosLeitores
    {
        public Guid Id { get; set; }
        [ForeignKey("Autor")]
        public Guid IdAutor { get; set; }
        [ForeignKey("Categoria")]
        public Guid IdCategoria { get; set; }
        public string Titulo { get; set; }
        public string Conteudo { get; set; }
        public int Paginas { get; set; }
        public virtual Autor Autor { get; set; }    
        public virtual Categoria Categoria { get; set; }  
        public virtual ICollection<LivroLeitor> LivroLeitores { get; set; }
    }
}

Controllers/LeitoresController.cs
using EsseJaLi.Data;
using EsseJaLi.Models;
using EsseJaLi.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EsseJaLi.Controllers
{
    public class LeitoresController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly EsseJaLiContext _context;

        public LeitoresController(SignInManager<IdentityUser> userHelper, UserManager<IdentityUser> userManager, EsseJaLiContext context)
        {
            _signInManager = userHelper;
            _userManager = userManager;
            _context = context;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            return View(new LoginLeitorViewModel()
            {
                ReturnUrl = returnUrl
            });
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(LoginLeitorViewModel loginVM)
        {
            if (!ModelState.IsValid)
                return View(loginVM);

            var user = await _userManager.FindByNameAsync(loginVM.UserName);

            if (user != null)
            {
                var result = await _signInManager.PasswordSignInAsync(user,
                    loginVM.Password, false, false);

                if (result.Succeeded)
                {
                    if (string.IsNullOrEmpty(loginVM.ReturnUrl))
                    {
                        return RedirectToAction("Index", "Livros");
                    }
                    return Redirect(loginVM.ReturnUrl);
                }
            }
            ModelState.AddModelError("", "Falha ao realizar o login!!");
            return View(loginVM);
        }//

        [AllowAnonymous]
        public IActionResult Register()
        {
            return View();
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var lista = new List<LeitorViewModel>();
            var leitores = await _context.Leitores.ToListAsync();
            var str_tfu = "";
            foreach (var l in leitores)
            {
                var premios = await _context.Premios.Where(p => p.IdLeitor == l.Id).ToListAsync();
                foreach (var p in premios)
                {
                    var categoria = await _context.Categorias.Where(c => c.Id == p.IdCategoria).FirstOrDefaultAsync();
                    str_tfu += " - " + categoria.Name;
                }

                var lvm = new LeitorViewModel()
                {
                    Nome = l.Nome,
                    Pontuacao = l.Pontuacao,
                    CatergoriLeitura = l.CategoriaLeitura,
                    LeitorTrofeus = " [ " + str_tfu + " ] "
                };
                lista.Add(lvm);
                str_tfu = "";
            }

            return View(lista.OrderByDescending(l => l.Pontuacao));
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterLeitorViewModel registroVM)
        {
            if (ModelState.IsValid)
            {
                var user = new Leitor
                {
                    UserName = registroVM.Username,
                    Nome = registroVM.FirstName + " " +
                    "" + registroVM.LastName,
                    Email = registroVM.Username,
                    PasswordHash = registroVM.Password,
                };
                if (!registroVM.Password.Equals(registroVM.Confirm))
                {
                    return View();
                }
                var result = await _userManager.CreateAsync(user, registroVM.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    //  await _userManager.AddToRoleAsync(user, "Member");
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    this.ModelState.AddModelError("Registro", "Falha ao registrar o usuário");
                }
            }
            return View(registroVM);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            // HttpContext.Session.Clear();
            // HttpContext.User = null;
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MarcarComoLido(LivrosLeitores livro)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User).ConfigureAwait(false);
            var livro_leitor = _context.LivrosLeitores.Where(l => l.IdLeitor == user.Id && l.IdLivro == livro.Id).FirstOrDefault();
            if (livro_leitor == null)
            {
                _context.LivrosLeitores.Add(new LivroLeitor()
                {
                    IdCategoria = livro.IdCategoria,
                    IdLivro = livro.Id,
                    IdLeitor = user.Id
                });
                await _context.SaveChangesAsync();

                int totalPages = livro.Paginas;
                int pontuacao = totalPages / 72;
                var categoria = _context.Categorias.Where(c => c.Id == livro.IdCategoria).FirstOrDefault();

                var leitor = _context.Leitores.Where(l => l.Id == user.Id).FirstOrDefault();

                leitor.Pontuacao = leitor.Pontuacao + pontuacao;
                _context.Leitores.Update(leitor);
                await _context.SaveChangesAsync();
                var lv = _context.LivrosLeitores.Where(lt => lt.IdLeitor == user.Id && lt.IdCategoria == livro.IdCategoria).ToList();

                if (lv.Count() >= 5)
                {
                    var ctl = await _context.Premios.Where(p => p.IdCategoria == livro.IdCategoria && p.IdLeitor == user.Id).FirstOrDefaultAsync();
                    if (ctl == null)
                    {
                        _context.Add(new Premio()
                        {
                            IdCategoria = livro.IdCategoria,
                            IdLeitor = user.Id
                        });
                        await _context.SaveChangesAsync();
                    }
                }
            }

            return RedirectToAction("Index", "Livros");
        }
    }
}

Controllers/LivrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EsseJaLi.Data;
using EsseJaLi.Models;
using Microsoft.AspNetCore.Authorization;

namespace EsseJaLi.Controllers
{
    public class LivrosController : Controller
    {
        private readonly EsseJaLiContext _context;

        public LivrosController(EsseJaLiContext context)
        {
            _context = context;
        }

        // GET: Livroes
        public async Task<IActionResult> Index()
        {
            var esseJaLiContext = _context.Livros.Include(l => l.Autor).Include(l => l.Categoria);
            return View(await esseJaLiContext.ToListAsync());
        }

        // GET: Livroes/Details/5
        [Authorize]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livros
                .Include(l => l.Autor)
                .Include(l => l.Categoria)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // GET: Livroes/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["IdAutor"] = new SelectList(_context.Autores, "Id", "Name");
            ViewData["IdCategoria"] = new SelectList(_context.Categorias, "Id", "Name");
            return View();
        }

        // POST: Livroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdAutor,IdCategoria,Titulo,Conteudo,Paginas")] LivrosLeitores livro)
        {
            if (ModelState.IsValid)
            {
                livro.Id = Guid.NewGuid();
                _context.Add(livro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAutor"] = new SelectList(_context.Autores, "Id", "Id", livro.IdAutor);
            ViewData["IdCategoria"] = new SelectList(_context.Categorias, "Id", "Id", livro.IdCategoria);
            return View(livro);
        }

        // GET: Livroes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livros.FindAsync(id);
            if (livro == null)
            {
                return NotFound();
            }
            ViewData["IdAutor"] = new SelectList(_context.Autores, "Id", "Name", livro.IdAutor);
            ViewData["IdCategoria"] = new SelectList(_context.Categorias, "Id", "Name" +
                "", livro.IdCategoria);
            return View(livro);
        }

        // POST: Livroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,IdAutor,IdCategoria,Titulo,Conteudo,Paginas")] LivrosLeitores livro)
        {
            if (id != livro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivroExists(livro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAutor"] = new SelectList(_context.Autores, "Name", "Id", livro.IdAutor);
            ViewData["IdCategoria"] = new SelectList(_context.Categorias, "Name", "Id", livro.IdCategoria);
            return View(livro);
        }

        // GET: Livroes/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livros
                .Include(l => l.Autor)
                .Include(l => l.Categoria)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // POST: Livroes/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var livro = await _context.Livros.FindAsync(id);
            _context.Livros.Remove(livro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LivroExists(Guid id)
        {
            return _context.Livros.Any(e => e.Id == id);
        }
    }
}

Views/Livros/Create.cshtml
@model EsseJaLi.Models.LivrosLeitores

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdAutor" class="control-label">Autor</label>
                <select asp-for="IdAutor" class ="form-control" asp-items="ViewBag.IdAutor"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdCategoria" class="control-label">Categoria</label>
                <select asp-for="IdCategoria" class ="form-control" asp-items="ViewBag.IdCategoria"></select>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Conteudo" class="control-label"></label>
                <textarea asp-for="Conteudo" class="form-control" rows="6" width="100%"></textarea>
                <span asp-validation-for="Conteudo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paginas" class="control-label"></label>
                <input asp-for="Paginas" class="form-control" />
                <span asp-validation-for="Paginas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Livros/Delete.cshtml
@model EsseJaLi.Models.LivrosLeitores

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Livro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Conteudo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Conteudo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paginas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paginas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Livros/Details.cshtml
@using EsseJaLi.ViewModels
@model EsseJaLi.Models.LivrosLeitores;

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Livro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Conteudo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Conteudo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paginas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paginas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria.Name)
        </dd>
    </dl>
</div>
<div>
   <form asp-controller="Leitores" asp-action="MarcarComoLido" method="post"> 
        <input type="hidden" asp-for="Id"  name="Id" id="ID">
         <input type="hidden" asp-for="Paginas"  name="Paginas" id="Paginas">
         <input type="hidden" asp-for="IdCategoria"  name="IdCategoria" id="IdCategoria">
         <input type="hidden" asp-for="Categoria"  name="Categoria" id="Categoria">
        <button class="btn mt-3 btn-success">Marcar como Lido</button> </form>
    <a asp-action="Index">Back to List</a>
</div>

Views/Livros/Edit.cshtml
@model EsseJaLi.Models.LivrosLeitores

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IdAutor" class="control-label">Autor</label>
                <select asp-for="IdAutor" class="form-control" asp-items="ViewBag.IdAutor"></select>
                <span asp-validation-for="IdAutor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCategoria" class="control-label">Categoria</label>
                <select asp-for="IdCategoria" class="form-control" asp-items="ViewBag.IdCategoria"></select>
                <span asp-validation-for="IdCategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Conteudo" class="control-label"></label>
                <input asp-for="Conteudo" class="form-control" />
                <span asp-validation-for="Conteudo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paginas" class="control-label"></label>
                <input asp-for="Paginas" class="form-control" />
                <span asp-validation-for="Paginas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Livros/Index.cshtml
@model IEnumerable<EsseJaLi.Models.LivrosLeitores>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>-->
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
         
            <th>
                @Html.DisplayNameFor(model => model.Paginas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
       
            <td>
                @Html.DisplayFor(modelItem => item.Paginas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.Name)
            </td>
            <td>
                 <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">Ver</a>
                <!--  <form asp-controller="Leitores" asp-action="MarcarComoLido" method="post"> 
        <input type="hidden" asp-for="@item.Id" name="Id" id="ID">
        <button class="btn mt-3 btn-warning">Lido</button> </form>
             |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>-->
            </td>
        </tr>
}
    </tbody>
</table>